name: github Checkout

on: [push] #event인 push와 같은 issues가 발생되었을 때 아래코드를 실행해라

jobs:
  build:

    runs-on: ubuntu-latest #event가 발생했을 때 실행되는 OS가 우분투이면 좋겠다는 의미

    steps:
    - uses: actions/checkout@v2 #다른 유저가 만든 action을 가져오는 방법 / https://github.com/actions/checkout 에서 action 확인 가능
    - name: Run pwd
      run: pwd
    - name: Run ls -al
      run: ls -al
